### ISSUE TITLE
Laravel Socialite

### ISSUE THREAD

**Issue by subdesign** [wuifdesign/laravel-multiauth#4]
What about Socialite Oauth login solituon? If I log in my user with Socialite (eg. Google), can I use Auth::googleuser()->check() or Auth::googleuser()->id ? Where googleuser is a user type in the auth settings.

**Comment by wuifdesign** [comment]
does the following work?

```
Auth::type('googleuser')->check() 
Auth::type('googleuser')->id() 
```

**Comment by subdesign** [comment]
Sorry, I forgot to report, it works !
