### ISSUE TITLE
Documentation misreading

### ISSUE THREAD

**Issue by subdesign** [wuifdesign/laravel-multiauth#5]
You have the following in the auth.php in the example:

```
    'reminder' => array(
        'email' => 'emails.auth.reminder',
        'table' => 'password_reminders',
        'expire' => 60,
    ),
```

but in Laravel 5.1 we have by default:

```
 'password' => [
        'email' => 'emails.password',
        'table' => 'password_resets',
        'expire' => 60,
    ],
```

so what's the difference between

```
'email' => 'users.emails.password',
```

and

```
'email' => 'emails.auth.reminder',
```

?
Which one to use?

**Comment by wuifdesign** [comment]
you are right the key should be "password" instead of "reminder", i fixed it in the readme.md

the difference between 

```
'email' => 'users.emails.password',
```

and 

```
'email' => 'emails.auth.reminder',
```

is just, which blade file is used for the email (`./users/email/password.blade.php` or `./emails/auth/reminder.blade.php`).

**Comment by subdesign** [comment]
Thanks
