### ISSUE TITLE
Auth::currentType() ever return user

### ISSUE THREAD

**Issue by Danjavia** [wuifdesign/laravel-multiauth#6]
Here is my code

```
elseif ( Auth::type( 'driver' )->attempt( $credentials ) ) {

        if ( $request->get( 'jsoncallback' ) )
            return response()->json( [ 'message' => 'logged', 'status' => 'ok', 'type' => Auth::currentType() ], 200 )->setCallback( $request->get( 'jsoncallback' ) );
        else
            return $this->response( [ 'message' => 'logged', 'status' => 'ok', 'type' => Auth::currentType() ], 200 );
    }
```

And result is

```
{
```

  "data": {
    "message": "logged",
    "status": "ok",
    "type": "user"
  }
}

**Comment by wuifdesign** [comment]
`Auth::currentType()` just returns the type set in the routes for the current route you are using. This can be set like this:

```
Route::get('/', array(
    'uses' => function () {
        return 'Hello World';
    },
    'middleware' => [ 'auth' ],
    'auth' => 'admin',
));
```

the **'auth' => 'admin',** tells which authadapter should be used. If set like this the `Auth::currentType()` will return: "admin". 

`Auth::type( 'driver' )` just override the type for this for this call, not the whole request.

**Comment by Danjavia** [comment]
Thanks for the answer.
